# Generated by Django 6.0.4 on 2026-04-23 09:38

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='expertise',
            field=models.CharField(choices=[('backend', 'Backend Developer'), ('frontend', 'Frontend Developer'), ('fullstack', 'Fullstack Developer'), ('mobile', 'Mobile Developer'), ('devops', 'DevOps Engineer'), ('data', 'Data Engineer / Data Scientist'), ('ai', 'AI / Machine Learning Engineer'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='prof_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.TextField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
