# Generated by Django 6.0.4 on 2026-04-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_managers_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.TextField(blank=True, default='prof_name', max_length=256, unique=True),
        ),
    ]
