# Generated by Django 6.0.4 on 2026-04-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
